sudo: required

language: python

env:
  - VER=0.23.1
  - VER=0.24.2
  - VER=0.25.1
  - VER=0.26.1
  - VER=0.27.2
  - VER=0.28.2
  - VER=1.0.1

services:
  - docker

before_install:
  - eval $(./set-travis-env.sh)
  - docker pull emccode/mesos-build-module-dev:${VER}

install:
  - docker run -ti -v $TRAVIS_BUILD_DIR/isolator/:/isolator emccode/mesos-build-module-dev:${VER} /bin/bash -c  '/usr/bin/make all && cp -p -v /isolator/build/.libs/libmesos_dvdi_isolator-${ISOLATOR_VERSION}.so /isolator/'
  - docker logs $(docker ps -l -q)
  - mv $TRAVIS_BUILD_DIR/isolator/libmesos_dvdi_isolator-${VER}.so $TRAVIS_BUILD_DIR/isolator/${SO_FILENAME}

script:
  - shasum $TRAVIS_BUILD_DIR/isolator/${SO_FILENAME}

before_deploy:
  - ls -la $TRAVIS_BUILD_DIR/isolator/
  - cat bintray-unstable-filtered.json

deploy:
  - provider: bintray
    file: bintray-unstable-filtered.json
    user: $BINTRAY_USER
    key: $BINTRAY_KEY
    skip_cleanup: true
